defaults:
  - _self_
  - face_detection_estimator: face_detection_retail_0004
  - gaze_estimator: gaze_estimation_adas_0002
  - head_pose_estimator: head-pose-estimation-adas-0001
  - eyes_state_estimator: open-closed-eye-0001
  - facial_landmarks_estimator: landmarks-regression-retail-0009.yaml

hydra:
  job:
    chdir: False

device: CPU
output_resolution: null
debug: True